'use client';import {useEffect,useState} from 'react';import {money} from '@/lib/format';
const empty={name:'',slug:'',description:'',price:'',compareAtPrice:'',stock:10,expectedStock:null,categoryId:'',imageUrl:'/products/default.svg',featured:false,active:true};
export default function AdminProducts(){const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[term,setTerm]=useState('');
 async function load(){const [p,c]=await Promise.all([fetch('/api/admin/products').then(r=>r.json()),fetch('/api/admin/categories').then(r=>r.json())]);setProducts(p.products||[]);setCategories(c.categories||[])}useEffect(()=>{load().catch(()=>setError('Could not load products.'))},[]);
 function create(){setEditing('');setForm({...empty,categoryId:categories[0]?.id||''});setError('');setShow(true)}function edit(p){setEditing(p.id);setForm({name:p.name,slug:p.slug,description:p.description,price:p.price,compareAtPrice:p.compareAtPrice??'',stock:p.stock,expectedStock:p.stock,categoryId:p.categoryId,imageUrl:p.imageUrl,featured:p.featured,active:p.active});setError('');setShow(true)}
 async function upload(e){const file=e.target.files?.[0];if(!file)return;setError('');setBusy(true);const payload=new FormData();payload.set('image',file);try{const r=await fetch('/api/admin/upload',{method:'POST',body:payload}),d=await r.json();if(!r.ok)throw Error(d.error);setForm(f=>({...f,imageUrl:d.url}));}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(editing?'/api/admin/products/'+editing:'/api/admin/products',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,price:Number(form.price),stock:Number(form.stock),compareAtPrice:form.compareAtPrice===''?null:Number(form.compareAtPrice)})}),d=await r.json();if(!r.ok)throw Error(d.error);setShow(false);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function archive(p){if(!confirm(`Hide "${p.name}" from the storefront?`))return;const r=await fetch('/api/admin/products/'+p.id,{method:'DELETE'});if(r.ok)load();else setError('Could not archive product.')}
 return <><div className="section-heading compact"><div><span className="eyebrow">INVENTORY CONTROL</span><h1>Product Management</h1><p className="muted">Create and edit products, prices, images and stock.</p></div><button className="btn btn-primary" onClick={create}>＋ Add Product</button></div><div className="admin-search"><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search by product name..."/></div>{error&&!show&&<p className="error-text">{error}</p>}{show&&<form className="panel admin-form" onSubmit={save}><div className="section-heading compact"><h2>{editing?'Edit Product':'New Product'}</h2><button type="button" onClick={()=>setShow(false)}>✕ Close</button></div><div className="form-grid"><label>Product Name *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug (leave blank to generate from name)<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Selling Price (৳) *<input required type="number" min="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Compare-at Price (৳)<input type="number" min="1" value={form.compareAtPrice} onChange={e=>setForm({...form,compareAtPrice:e.target.value})}/></label><label>Stock *<input required type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label>Category *<select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Select a category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="wide">Description<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Image URL (HTTPS or local path)<input value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label><label>Upload Image (max 3MB)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><div className="admin-preview"><img src={form.imageUrl||'/products/default.svg'} alt="Preview"/></div><label className="checkbox-label"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured Product</label><label className="checkbox-label"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Visible in Store</label></div>{error&&<p className="error-text">{error}</p>}<button className="btn btn-primary" disabled={busy}>{busy?'Saving...':'Save Product'}</button></form>}
 <div className="panel table-wrap"><table><thead><tr><th>Image</th><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{products.filter(p=>p.name.toLowerCase().includes(term.toLowerCase())).map(p=><tr key={p.id}><td><img className="table-thumb" src={p.imageUrl} alt=""/></td><td><b>{p.name}</b><small>{p.category?.name}</small></td><td>{money(p.price,'en-BD')}</td><td>{p.stock}</td><td><span className="status">{p.active?'Active':'Hidden'}</span></td><td><div className="inline-actions"><button onClick={()=>edit(p)}>Edit</button><button className="danger-text" onClick={()=>archive(p)} disabled={!p.active}>Archive</button></div></td></tr>)}</tbody></table></div></>;
}
