'use client';
import { useEffect, useMemo, useState } from 'react';
const empty={title:'',slug:'',description:'',badge:'COMBO OFFER',imageUrl:'',active:true,pricingType:'FIXED_PRICE',bundlePrice:'',discountValue:10,items:[],insideDhakaFee:70,outsideDhakaFee:130,allowCoupon:true,startsAt:'',expiresAt:'',usageLimit:'',perCustomerLimit:5};
function localDate(v){if(!v)return'';const d=new Date(v),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function slugify(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
function money(v){return `৳${Number(v||0).toLocaleString('en-US')}`}
export default function AdminBundles(){
 const [data,setData]=useState({bundles:[],products:[]}),[form,setForm]=useState(empty),[editing,setEditing]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState('');
 async function load(){const r=await fetch('/api/admin/bundles',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load bundles.');setData(d)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const shown=useMemo(()=>data.bundles.filter(b=>`${b.title} ${b.slug}`.toLowerCase().includes(search.toLowerCase())),[data.bundles,search]);
 const productMap=useMemo(()=>new Map(data.products.map(p=>[p.id,p])),[data.products]);
 const regular=useMemo(()=>form.items.reduce((s,it)=>s+Number(productMap.get(it.productId)?.price||0)*Number(it.quantity||1),0),[form.items,productMap]);
 const offer=useMemo(()=>{if(form.pricingType==='FIXED_PRICE')return Number(form.bundlePrice||0);if(form.pricingType==='PERCENTAGE')return regular-Math.floor(regular*Math.min(100,Number(form.discountValue||0))/100);return Math.max(0,regular-Number(form.discountValue||0))},[form,regular]);
 const f=(k,v)=>setForm(p=>({...p,[k]:v}));
 function toggleProduct(id){setForm(p=>{const exists=p.items.find(x=>x.productId===id);return{...p,items:exists?p.items.filter(x=>x.productId!==id):[...p.items,{productId:id,quantity:1}]}})}
 function qty(id,v){setForm(p=>({...p,items:p.items.map(x=>x.productId===id?{...x,quantity:Math.max(1,Math.min(20,Number(v||1)))}:x)}))}
 function edit(b){setEditing(b.id);setForm({...empty,...b,startsAt:localDate(b.startsAt),expiresAt:localDate(b.expiresAt),bundlePrice:b.bundlePrice??'',usageLimit:b.usageLimit??'',items:Array.isArray(b.items)?b.items:[]});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch(editing?`/api/admin/bundles/${editing}`:'/api/admin/bundles',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save bundle.');setMessage(editing?'Bundle updated.':'Bundle created.');setEditing('');setForm(empty);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(id){if(!confirm('Delete this bundle? Bundles with order history will be deactivated instead.'))return;const r=await fetch(`/api/admin/bundles/${id}`,{method:'DELETE'});const d=await r.json();if(!r.ok){setError(d.error||'Could not delete bundle.');return}setMessage(d.deactivated?'Bundle has order history, so it was deactivated.':'Bundle deleted.');await load()}
 return <div style={{display:'grid',gap:18}}>
  <div><span className="eyebrow">SALES · BUNDLES</span><h1 style={{marginBottom:5}}>Bundle & Combo Offers</h1><p className="muted">Create combo deals with fixed bundle prices or automatic discounts, then use them in landing pages.</p></div>
  {error&&<p className="error-text">{error}</p>}{message&&<p className="success-text">{message}</p>}
  <form className="panel" onSubmit={save} style={{display:'grid',gap:14}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><h2 style={{margin:0}}>{editing?'Edit Bundle':'Create Bundle'}</h2>{editing&&<button type="button" className="btn btn-outline" onClick={()=>{setEditing('');setForm(empty)}}>Cancel Edit</button>}</div>
   <div className="form-grid">
    <label>Bundle Title *<input required value={form.title} onChange={e=>{f('title',e.target.value);if(!editing&&!form.slug)f('slug',slugify(e.target.value))}} placeholder="Gift Combo Deal"/></label>
    <label>URL Slug *<input required value={form.slug} onChange={e=>f('slug',slugify(e.target.value))} placeholder="gift-combo-deal"/></label>
    <label>Badge<input value={form.badge} onChange={e=>f('badge',e.target.value)} placeholder="SAVE MORE"/></label>
    <label>Pricing Type<select value={form.pricingType} onChange={e=>f('pricingType',e.target.value)}><option value="FIXED_PRICE">Fixed Bundle Price</option><option value="PERCENTAGE">Percentage Discount</option><option value="FIXED_DISCOUNT">Fixed BDT Discount</option></select></label>
    {form.pricingType==='FIXED_PRICE'?<label>Bundle Price (BDT) *<input required type="number" min="1" value={form.bundlePrice} onChange={e=>f('bundlePrice',e.target.value)}/></label>:<label>{form.pricingType==='PERCENTAGE'?'Discount %':'Discount BDT'} *<input required type="number" min="1" max={form.pricingType==='PERCENTAGE'?100:10000000} value={form.discountValue} onChange={e=>f('discountValue',e.target.value)}/></label>}
    <label>Inside Dhaka Delivery<input type="number" min="0" value={form.insideDhakaFee} onChange={e=>f('insideDhakaFee',e.target.value)}/></label>
    <label>Outside Dhaka Delivery<input type="number" min="0" value={form.outsideDhakaFee} onChange={e=>f('outsideDhakaFee',e.target.value)}/></label>
    <label>Starts At<input type="datetime-local" value={form.startsAt} onChange={e=>f('startsAt',e.target.value)}/></label>
    <label>Expires At<input type="datetime-local" value={form.expiresAt} onChange={e=>f('expiresAt',e.target.value)}/></label>
    <label>Overall Order Limit<input type="number" min="1" value={form.usageLimit} onChange={e=>f('usageLimit',e.target.value)} placeholder="Unlimited"/></label>
    <label>Per Phone Limit<input type="number" min="0" value={form.perCustomerLimit} onChange={e=>f('perCustomerLimit',e.target.value)}/></label>
    <label className="wide">Bundle Image URL / Path<input value={form.imageUrl} onChange={e=>f('imageUrl',e.target.value)} placeholder="/images/combo.webp or https://..."/></label>
    <label className="wide">Description<textarea rows="3" value={form.description} onChange={e=>f('description',e.target.value)} placeholder="What is included and why this combo is valuable?"/></label>
   </div>
   <div><b>Select Products & Quantity</b><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:8,marginTop:9,maxHeight:340,overflow:'auto'}}>{data.products.map(p=>{const item=form.items.find(x=>x.productId===p.id);return <div key={p.id} style={{display:'grid',gridTemplateColumns:'auto 1fr 72px',alignItems:'center',gap:8,border:'1px solid #e1e8df',padding:9,borderRadius:9}}><input type="checkbox" checked={!!item} onChange={()=>toggleProduct(p.id)}/><span><b>{p.name}</b><small style={{display:'block'}}>{money(p.price)} · Stock {p.stock}</small></span><input type="number" min="1" max="20" disabled={!item} value={item?.quantity||1} onChange={e=>qty(p.id,e.target.value)}/></div>})}</div></div>
   <div style={{display:'flex',gap:18,flexWrap:'wrap'}}><label><input type="checkbox" checked={form.active} onChange={e=>f('active',e.target.checked)}/> Active</label><label><input type="checkbox" checked={form.allowCoupon} onChange={e=>f('allowCoupon',e.target.checked)}/> Allow coupon stacking</label></div>
   <div style={{padding:12,border:'1px solid #dce7d8',borderRadius:10,background:'#f8fbf6'}}><b>Price Preview</b><div style={{display:'flex',gap:18,flexWrap:'wrap',marginTop:5}}><span>Regular: <del>{money(regular)}</del></span><strong>Bundle: {money(Math.max(0,offer))}</strong><span>Save: {money(Math.max(0,regular-offer))}</span></div></div>
   <button className="btn btn-primary" disabled={busy} style={{justifySelf:'start'}}>{busy?'Saving...':editing?'Update Bundle':'Create Bundle'}</button>
  </form>
  <section className="panel"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><h2 style={{margin:0}}>Bundles</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search bundles..." style={{maxWidth:260}}/></div><div style={{overflowX:'auto',marginTop:12}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">Bundle</th><th align="left">Pricing</th><th align="left">Status</th><th align="left">Orders</th><th align="right">Actions</th></tr></thead><tbody>{shown.map(b=><tr key={b.id} style={{borderTop:'1px solid #e7ece5'}}><td style={{padding:'12px 4px'}}><b>{b.title}</b><small style={{display:'block'}}>/bundle/{b.slug}</small></td><td>{b.pricingType==='FIXED_PRICE'?money(b.bundlePrice):b.pricingType==='PERCENTAGE'?`${b.discountValue}% off`:`${money(b.discountValue)} off`}</td><td>{b.active?'Active':'Inactive'}</td><td>{b.usedCount}{b.usageLimit!=null?` / ${b.usageLimit}`:''}</td><td align="right"><div style={{display:'flex',gap:6,justifyContent:'flex-end'}}><a className="btn btn-outline" href={`/bundle/${b.slug}`} target="_blank">View</a><button type="button" className="btn btn-outline" onClick={()=>navigator.clipboard?.writeText(b.slug)}>Copy Slug</button><button type="button" className="btn btn-outline" onClick={()=>edit(b)}>Edit</button><button type="button" className="btn btn-outline" onClick={()=>remove(b.id)}>Delete</button></div></td></tr>)}{!shown.length&&<tr><td colSpan="5" className="muted" style={{padding:20,textAlign:'center'}}>No bundles found.</td></tr>}</tbody></table></div></section>
 </div>
}
