'use client';
import {useEffect,useState} from 'react';
const initial={googleEnabled:false,googleAdsId:'',googlePurchaseLabel:'',ga4MeasurementId:'',metaEnabled:false,metaPixelId:''};
export default function AdminAdsTracking(){
  const [form,setForm]=useState(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
  useEffect(()=>{const controller=new AbortController();fetch('/api/admin/ads-tracking',{cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Cannot load settings');return data}).then(data=>setForm(data.settings)).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>setLoading(false));return ()=>controller.abort()},[]);
  function change(key,val){setForm(f=>({...f,[key]:val}));setSuccess('');setError('')}
  async function save(e){e.preventDefault();setSaving(true);setError('');setSuccess('');try{const r=await fetch('/api/admin/ads-tracking',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw Error(data.error||'Save failed');setForm(data.settings);setSuccess('Tracking settings saved. Changes will apply to new visitors.')}catch(e){setError(e.message)}finally{setSaving(false)}}
  if(loading)return <div className="panel">Loading tracking settings...</div>;
  return <><span className="eyebrow">MARKETING INTEGRATIONS</span><h1>Ads Tracking Settings</h1><p className="muted">Enter Google Ads, GA4 and Meta Pixel IDs. Do not paste code snippets, access tokens or API secrets.</p><form className="admin-ads" onSubmit={save}>
    <section className="panel ads-panel"><div className="ads-heading"><div><h2>Google Ads &amp; Analytics</h2><p className="muted">Google tag, GA4 and order conversions</p></div><label className="ads-switch"><input type="checkbox" checked={form.googleEnabled} onChange={e=>change('googleEnabled',e.target.checked)}/> Enable</label></div><div className="form-grid"><label>Google Ads Conversion ID<input placeholder="AW-123456789" autoComplete="off" value={form.googleAdsId} onChange={e=>change('googleAdsId',e.target.value)}/><small>Find your AW-ID in Google Ads → Goals → Conversions → Tag setup.</small></label><label>Purchase Conversion Label<input placeholder="AbCDeFg-hijk_123" autoComplete="off" value={form.googlePurchaseLabel} onChange={e=>change('googlePurchaseLabel',e.target.value)}/><small>Label for an order-placed conversion, used together with your AW-ID.</small></label><label className="wide">GA4 Measurement ID (optional)<input placeholder="G-XXXXXXXXXX" autoComplete="off" value={form.ga4MeasurementId} onChange={e=>change('ga4MeasurementId',e.target.value)}/><small>Sends GA4 page_view, view_item, add_to_cart, begin_checkout and purchase events.</small></label></div></section>
    <section className="panel ads-panel"><div className="ads-heading"><div><h2>Facebook / Meta Pixel</h2><p className="muted">Pixel / Dataset ID from Meta Events Manager</p></div><label className="ads-switch"><input type="checkbox" checked={form.metaEnabled} onChange={e=>change('metaEnabled',e.target.checked)}/> Enable</label></div><div className="form-grid"><label className="wide">Meta Pixel ID<input placeholder="123456789012345" autoComplete="off" value={form.metaPixelId} onChange={e=>change('metaPixelId',e.target.value)}/><small>Numeric Pixel ID only. No access token is needed.</small></label></div></section>
    <section className="panel ads-panel"><h2>Events &amp; Privacy</h2><div className="ads-events"><span>PageView</span><span>ViewContent</span><span>AddToCart</span><span>InitiateCheckout</span><span>Purchase (BDT)</span></div><p className="muted">Tracking scripts load only after visitor consent. Admin, account and tracking pages are excluded. Purchase events indicate an order was placed (COD), not payment or delivery.</p></section>
    {error&&<p className="error-text" role="alert">{error}</p>}{success&&<p className="success-text" role="status">{success}</p>}<button type="submit" className="btn btn-primary" disabled={saving}>{saving?'Saving...':'Save Tracking Settings'}</button>
    <p className="tiny-muted">Test with Google Tag Assistant, GA4 DebugView and Meta Events Manager → Test Events. Avoid installing the same IDs through Google Tag Manager as duplicate events may occur.</p>
  </form></>;
}
