'use client';
import { useMemo, useState } from 'react';
import CouponApplyBox from './CouponApplyBox';
import styles from './BundleOffer.module.css';
function money(v){return `৳${Number(v||0).toLocaleString('en-US')}`}
export default function BundleOrderForm({bundle,compact=false}){
 const [quantity,setQuantity]=useState(1),[customer,setCustomer]=useState({name:'',phone:'',email:'',address:'',city:'',zone:'DHAKA',note:'',website:''}),[coupon,setCoupon]=useState({code:'',discountAmount:0}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);
 const items=useMemo(()=>bundle.items.map(i=>({productId:i.productId,quantity:Number(i.quantity||1)*quantity})),[bundle.items,quantity]);
 const regular=Number(bundle.pricing.regularSingle||0)*quantity,bundleTotal=Number(bundle.pricing.offerSingle||0)*quantity,bundleDiscount=Math.max(0,regular-bundleTotal),couponDiscount=Math.min(bundleTotal,Number(coupon.discountAmount||0)),shipping=customer.zone==='DHAKA'?Number(bundle.insideDhakaFee||0):Number(bundle.outsideDhakaFee||0),total=Math.max(0,bundleTotal-couponDiscount)+shipping;
 const f=(k,v)=>setCustomer(p=>({...p,[k]:v}));
 async function submit(e){e.preventDefault();if(busy||!bundle.available)return;setBusy(true);setError('');setResult(null);try{const q=new URLSearchParams(window.location.search);const r=await fetch('/api/bundle-orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:bundle.slug,quantity,couponCode:coupon.code,customer,tracking:{source:q.get('utm_source')||'',medium:q.get('utm_medium')||'',campaign:q.get('utm_campaign')||'',referrer:document.referrer||''}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Order failed.');setResult(d.order);try{if(typeof window.fbq==='function')window.fbq('track','Purchase',{value:Number(d.order?.total||0),currency:'BDT'});if(typeof window.gtag==='function')window.gtag('event','purchase',{transaction_id:d.order?.orderNo||'',value:Number(d.order?.total||0),currency:'BDT'})}catch{}}catch(e){setError(e.message||'Could not place order.')}finally{setBusy(false)}}
 if(result)return <div className={styles.success}><b>✓ অর্ডার গ্রহণ করা হয়েছে</b><p>Order No: <strong>{result.orderNo}</strong></p><p>Total: <strong>{money(result.total)}</strong></p></div>;
 return <form onSubmit={submit} className={`${styles.orderForm} ${compact?styles.compact:''}`}>
  {!bundle.available&&<div className={styles.error}>{bundle.unavailableReason||'This offer is unavailable.'}</div>}{error&&<div className={styles.error}>{error}</div>}
  <div className={styles.qtyRow}><b>Combo Quantity</b><div><button type="button" onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><input type="number" min="1" max="10" value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(10,Number(e.target.value||1))))}/><button type="button" onClick={()=>setQuantity(Math.min(10,quantity+1))}>+</button></div></div>
  <div className={styles.fields}><label>নাম *<input required value={customer.name} onChange={e=>f('name',e.target.value)} placeholder="আপনার নাম"/></label><label>মোবাইল *<input required inputMode="tel" value={customer.phone} onChange={e=>f('phone',e.target.value)} placeholder="01XXXXXXXXX"/></label><label>জেলা / শহর *<input required value={customer.city} onChange={e=>f('city',e.target.value)} placeholder="Dhaka / ..."/></label><label className={styles.full}>সম্পূর্ণ ঠিকানা *<textarea required rows="3" value={customer.address} onChange={e=>f('address',e.target.value)}/></label><div className={styles.full}><b>Delivery Area</b><div className={styles.zones}><label><input type="radio" checked={customer.zone==='DHAKA'} onChange={()=>f('zone','DHAKA')}/> ঢাকার ভিতরে — {money(bundle.insideDhakaFee)}</label><label><input type="radio" checked={customer.zone==='OUTSIDE'} onChange={()=>f('zone','OUTSIDE')}/> ঢাকার বাইরে — {money(bundle.outsideDhakaFee)}</label></div></div><label className={styles.full}>Order Note (optional)<textarea rows="2" value={customer.note} onChange={e=>f('note',e.target.value)}/></label><input className={styles.honey} tabIndex="-1" value={customer.website} onChange={e=>f('website',e.target.value)}/></div>
  {bundle.allowCoupon&&<CouponApplyBox items={items} phone={customer.phone} pageId="" onChange={setCoupon}/>} 
  <div className={styles.summary}><div><span>Regular Price</span><del>{money(regular)}</del></div><div><span>Bundle Discount</span><strong>−{money(bundleDiscount)}</strong></div>{couponDiscount>0&&<div><span>Coupon {coupon.code}</span><strong>−{money(couponDiscount)}</strong></div>}<div><span>Delivery</span><strong>{money(shipping)}</strong></div><div className={styles.grand}><span>Total</span><strong>{money(total)}</strong></div><small>Cash on Delivery</small></div>
  <button className={styles.submit} disabled={busy||!bundle.available}>{busy?'অর্ডার হচ্ছে...':'কম্বো অর্ডার কনফার্ম করুন'}</button>
 </form>
}
