ALTER TABLE "Category"
ADD COLUMN IF NOT EXISTS "imageUrl"
TEXT NOT NULL DEFAULT '/categories/default.svg';

ALTER TABLE "Category"
ADD COLUMN IF NOT EXISTS "updatedAt"
TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
